name: dart_auth
description: "An auth lib for flutter web and mobile"
version: 0.0.4

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  flutter_gen: ^5.8.0

flutter:
  uses-material-design: true
  generate: true